databases:
  - name: microfinance-db
    databaseName: microfinance
    user: microfinance

services:
  - type: web
    name: microfinance-app
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage_local.py migrate && python manage_local.py collectstatic --noinput"
    startCommand: "gunicorn microfinance.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.10
      - key: DATABASE_URL
        fromDatabase:
          name: microfinance-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
